-- Inserir áreas de atuação do CFM como especialidades
-- Extraídas do campo RQE dos leads + lista oficial CFM
-- Estas são sub-especialidades que o Ewerton precisa para filtros de disparo

INSERT INTO especialidades (nome, area, aliases) VALUES
  ('ADMINISTRAÇÃO EM SAÚDE', 'apoio', ARRAY['administração em saúde', 'administracao em saude']),
  ('ADMINISTRAÇÃO HOSPITALAR', 'apoio', ARRAY['administração hospitalar', 'administracao hospitalar']),
  ('ALERGIA E IMUNOLOGIA PEDIÁTRICA', 'clinica', ARRAY['alergia e imunologia pediátrica', 'alergia e imunologia pediatrica', 'imunologia pediatrica']),
  ('ANGIORRADIOLOGIA E CIRURGIA ENDOVASCULAR', 'cirurgica', ARRAY['angiorradiologia', 'cirurgia endovascular', 'angiorradiologia e cirurgia endovascular']),
  ('ATENDIMENTO AO QUEIMADO', 'cirurgica', ARRAY['atendimento ao queimado', 'queimados']),
  ('AUDITORIA MÉDICA', 'apoio', ARRAY['auditoria médica', 'auditoria medica']),
  ('BRONCOESOFAGOLOGIA', 'diagnostica', ARRAY['broncoesofagologia']),
  ('CANCEROLOGIA', 'clinica', ARRAY['cancerologia', 'cancerologista']),
  ('CANCEROLOGIA CIRÚRGICA', 'cirurgica', ARRAY['cancerologia cirúrgica', 'cancerologia cirurgica', 'cancerologia/cancerologia cirúrgica']),
  ('CANCEROLOGIA PEDIÁTRICA', 'clinica', ARRAY['cancerologia pediátrica', 'cancerologia pediatrica', 'cancerologia/cancerologia pediátrica']),
  ('CARDIOLOGIA PEDIÁTRICA', 'clinica', ARRAY['cardiologia pediátrica', 'cardiologia pediatrica', 'cardiopediatria']),
  ('CIRURGIA BARIÁTRICA', 'cirurgica', ARRAY['cirurgia bariátrica', 'cirurgia bariatrica', 'bariatrica']),
  ('CIRURGIA CRÂNIO-MAXILO-FACIAL', 'cirurgica', ARRAY['cirurgia crânio-maxilo-facial', 'cirurgia cranio-maxilo-facial', 'bucomaxilo']),
  ('CIRURGIA DA COLUNA', 'cirurgica', ARRAY['cirurgia da coluna', 'coluna']),
  ('CIRURGIA DO TRAUMA', 'cirurgica', ARRAY['cirurgia do trauma', 'trauma cirurgico']),
  ('CIRURGIA GASTROENTEROLÓGICA', 'cirurgica', ARRAY['cirurgia gastroenterológica', 'cirurgia gastroenterologica']),
  ('CIRURGIA VIDEOLAPAROSCÓPICA', 'cirurgica', ARRAY['cirurgia videolaparoscópica', 'cirurgia videolaparoscopica', 'videolaparoscopia', 'laparoscopia']),
  ('CITOPATOLOGIA', 'diagnostica', ARRAY['citopatologia', 'citopatologista']),
  ('COLONOSCOPIA', 'diagnostica', ARRAY['colonoscopia']),
  ('DENSITOMETRIA ÓSSEA', 'diagnostica', ARRAY['densitometria óssea', 'densitometria ossea', 'densitometria']),
  ('DOR', 'clinica', ARRAY['dor', 'tratamento da dor', 'medicina da dor', 'terapia da dor']),
  ('ECOCARDIOGRAFIA', 'diagnostica', ARRAY['ecocardiografia', 'eco', 'ecocardiografista']),
  ('ECOCARDIOGRAFIA PEDIÁTRICA', 'diagnostica', ARRAY['ecocardiografia pediátrica', 'ecocardiografia pediatrica']),
  ('ECOGRAFIA VASCULAR COM DOPPLER', 'diagnostica', ARRAY['ecografia vascular com doppler', 'doppler vascular', 'ecografia vascular']),
  ('ELETROENCEFALOGRAFIA', 'diagnostica', ARRAY['eletroencefalografia', 'eletrencefalografia', 'eeg']),
  ('ELETROFISIOLOGIA CLÍNICA INVASIVA', 'diagnostica', ARRAY['eletrofisiologia clínica invasiva', 'eletrofisiologia clinica invasiva', 'eletrofisiologia']),
  ('ELETRONEUROMIOGRAFIA', 'diagnostica', ARRAY['eletroneuromiografia', 'enmg']),
  ('EMERGÊNCIA PEDIÁTRICA', 'clinica', ARRAY['emergência pediátrica', 'emergencia pediatrica']),
  ('ENDOCRINOLOGIA PEDIÁTRICA', 'clinica', ARRAY['endocrinologia pediátrica', 'endocrinologia pediatrica', 'endocrino pediatrico']),
  ('ENDOSCOPIA GINECOLÓGICA', 'diagnostica', ARRAY['endoscopia ginecológica', 'endoscopia ginecologica']),
  ('ENDOSCOPIA RESPIRATÓRIA', 'diagnostica', ARRAY['endoscopia respiratória', 'endoscopia respiratoria', 'endoscopia peroral', 'endoscopia peroral vias aéreas']),
  ('ERGOMETRIA', 'diagnostica', ARRAY['ergometria', 'teste ergométrico']),
  ('ESTIMULAÇÃO CARDÍACA ELETRÔNICA IMPLANTÁVEL', 'cirurgica', ARRAY['estimulação cardíaca eletrônica implantável', 'estimulacao cardiaca eletronica implantavel', 'marca-passo']),
  ('GASTROENTEROLOGIA PEDIÁTRICA', 'clinica', ARRAY['gastroenterologia pediátrica', 'gastroenterologia pediatrica', 'gastropediatria']),
  ('HANSENOLOGIA', 'clinica', ARRAY['hansenologia', 'hansenologista']),
  ('HEMATOLOGIA E HEMOTERAPIA PEDIÁTRICA', 'clinica', ARRAY['hematologia e hemoterapia pediátrica', 'hematologia e hemoterapia pediatrica', 'hematologia pediatrica']),
  ('HEMODINÂMICA E CARDIOLOGIA INTERVENCIONISTA', 'diagnostica', ARRAY['hemodinâmica e cardiologia intervencionista', 'hemodinamica e cardiologia intervencionista', 'hemodinamica', 'cardiologia intervencionista']),
  ('HEPATOLOGIA', 'clinica', ARRAY['hepatologia', 'hepatologista']),
  ('INFECTOLOGIA PEDIÁTRICA', 'clinica', ARRAY['infectologia pediátrica', 'infectologia pediatrica', 'infecto pediatrico']),
  ('MAMOGRAFIA', 'diagnostica', ARRAY['mamografia']),
  ('MEDICINA AEROESPACIAL', 'apoio', ARRAY['medicina aeroespacial']),
  ('MEDICINA DE URGÊNCIA', 'clinica', ARRAY['medicina de urgência', 'medicina de urgencia', 'urgencista']),
  ('MEDICINA DO ADOLESCENTE', 'clinica', ARRAY['medicina do adolescente', 'adolescência', 'adolescencia', 'hebiatria']),
  ('MEDICINA DO SONO', 'clinica', ARRAY['medicina do sono', 'sono']),
  ('MEDICINA FETAL', 'clinica', ARRAY['medicina fetal']),
  ('MEDICINA INTENSIVA PEDIÁTRICA', 'clinica', ARRAY['medicina intensiva pediátrica', 'medicina intensiva pediatrica', 'intensivista pediátrico', 'intensivista pediatrico', 'uti pediátrica', 'uti pediatrica', 'terapia intensiva pediátrica', 'terapia intensiva pediatrica']),
  ('MEDICINA INTENSIVA NEONATAL', 'clinica', ARRAY['medicina intensiva neonatal', 'uti neonatal', 'neonatologia intensiva']),
  ('MEDICINA PALIATIVA', 'clinica', ARRAY['medicina paliativa', 'cuidados paliativos', 'paliativista']),
  ('MEDICINA SANITÁRIA', 'apoio', ARRAY['medicina sanitária', 'medicina sanitaria', 'sanitarista']),
  ('NEFROLOGIA PEDIÁTRICA', 'clinica', ARRAY['nefrologia pediátrica', 'nefrologia pediatrica', 'nefro pediatrico']),
  ('NEONATOLOGIA', 'clinica', ARRAY['neonatologia', 'neonatologista', 'neonatal']),
  ('NEUROFISIOLOGIA CLÍNICA', 'diagnostica', ARRAY['neurofisiologia clínica', 'neurofisiologia clinica', 'neurofisiologia']),
  ('NEUROLOGIA PEDIÁTRICA', 'clinica', ARRAY['neurologia pediátrica', 'neurologia pediatrica', 'neuropediatria', 'neuropediatra']),
  ('NEURORRADIOLOGIA DIAGNÓSTICA', 'diagnostica', ARRAY['neurorradiologia diagnóstica', 'neurorradiologia diagnostica']),
  ('NEURORRADIOLOGIA TERAPÊUTICA', 'diagnostica', ARRAY['neurorradiologia terapêutica', 'neurorradiologia terapeutica']),
  ('NUTRIÇÃO PARENTERAL E ENTERAL', 'clinica', ARRAY['nutrição parenteral e enteral', 'nutricao parenteral e enteral', 'nutrição parenteral']),
  ('NUTRIÇÃO PARENTERAL E ENTERAL PEDIÁTRICA', 'clinica', ARRAY['nutrição parenteral e enteral pediátrica', 'nutricao parenteral e enteral pediatrica']),
  ('NUTROLOGIA PEDIÁTRICA', 'clinica', ARRAY['nutrologia pediátrica', 'nutrologia pediatrica']),
  ('ONCOLOGIA PEDIÁTRICA', 'clinica', ARRAY['oncologia pediátrica', 'oncologia pediatrica', 'oncopediatria']),
  ('PERÍCIA MÉDICA', 'apoio', ARRAY['perícia médica', 'pericia medica', 'perito medico']),
  ('PNEUMOLOGIA PEDIÁTRICA', 'clinica', ARRAY['pneumologia pediátrica', 'pneumologia pediatrica', 'pneumo pediatrico']),
  ('PSIQUIATRIA DA INFÂNCIA E ADOLESCÊNCIA', 'clinica', ARRAY['psiquiatria da infância e adolescência', 'psiquiatria da infancia e adolescencia', 'psiquiatria infantil', 'psiquiatria pediátrica']),
  ('PSIQUIATRIA FORENSE', 'apoio', ARRAY['psiquiatria forense']),
  ('RADIOLOGIA INTERVENCIONISTA E ANGIORRADIOLOGIA', 'diagnostica', ARRAY['radiologia intervencionista e angiorradiologia', 'radiologia intervencionista', 'angiorradiologia intervencionista']),
  ('REPRODUÇÃO ASSISTIDA', 'clinica', ARRAY['reprodução assistida', 'reproducao assistida', 'fertilização']),
  ('REPRODUÇÃO HUMANA', 'clinica', ARRAY['reprodução humana', 'reproducao humana']),
  ('RESSONÂNCIA MAGNÉTICA', 'diagnostica', ARRAY['ressonância magnética', 'ressonancia magnetica', 'rm']),
  ('REUMATOLOGIA PEDIÁTRICA', 'clinica', ARRAY['reumatologia pediátrica', 'reumatologia pediatrica', 'reumato pediatrico']),
  ('SEXOLOGIA', 'clinica', ARRAY['sexologia', 'sexologista']),
  ('TOXICOLOGIA MÉDICA', 'clinica', ARRAY['toxicologia médica', 'toxicologia medica', 'toxicologista']),
  ('TRANSPLANTE DE MEDULA ÓSSEA', 'clinica', ARRAY['transplante de medula óssea', 'transplante de medula ossea', 'tmo']),
  ('ULTRASSONOGRAFIA GERAL', 'diagnostica', ARRAY['ultrassonografia geral', 'ultrassonografia', 'ultrassom', 'usg']),
  ('ULTRASSONOGRAFIA EM GINECOLOGIA E OBSTETRÍCIA', 'diagnostica', ARRAY['ultrassonografia em ginecologia e obstetrícia', 'ultrassonografia em ginecologia e obstetricia', 'usg ginecológica'])
ON CONFLICT (nome) DO NOTHING;
