-- Popular aliases e area para cada especialidade
UPDATE especialidades SET aliases = '{anestesiologia,anestesio,anestesiologista}', area = 'clinica' WHERE nome = 'ANESTESIOLOGISTA';
UPDATE especialidades SET aliases = '{cardiologia,cardio,cardiologista}', area = 'clinica' WHERE nome = 'CARDIOLOGIA';
UPDATE especialidades SET aliases = '{cirurgia cardiovascular,cirurgiao cardiovascular}', area = 'cirurgica' WHERE nome = 'CIRURGIA CARDIOVASCULAR';
UPDATE especialidades SET aliases = '{cirurgia geral,cirurgiao geral,cirurgiao}', area = 'cirurgica' WHERE nome = 'CIRURGIA GERAL';
UPDATE especialidades SET aliases = '{cirurgia plastica,cirurgiao plastico}', area = 'cirurgica' WHERE nome = 'CIRURGIA PLÁSTICA';
UPDATE especialidades SET aliases = '{cirurgia vascular,cirurgiao vascular}', area = 'cirurgica' WHERE nome = 'CIRURGIA VASCULAR';
UPDATE especialidades SET aliases = '{clinica medica,clinico,clinico geral,clinica geral,generalista clinico,clinica,clinica geral / generalista,clinico vermelha}', area = 'clinica' WHERE nome = 'CLÍNICA MÉDICA';
UPDATE especialidades SET aliases = '{dermatologia,dermatologista,dermato}', area = 'clinica' WHERE nome = 'DERMATOLOGIA';
UPDATE especialidades SET aliases = '{endocrinologia,endocrinologista,endocrino,endocrinologia e metabologia}', area = 'clinica' WHERE nome = 'ENDOCRINOLOGIA E METABOLOGIA';
UPDATE especialidades SET aliases = '{gastroenterologia,gastro,gastroenterologista}', area = 'clinica' WHERE nome = 'GASTROENTEROLOGIA';
UPDATE especialidades SET aliases = '{ginecologia,obstetricia,ginecologia e obstetricia,ginecologista,obstetra,go}', area = 'clinica' WHERE nome = 'GINECOLOGIA E OBSTETRÍCIA';
UPDATE especialidades SET aliases = '{hematologia,hemoterapia,hematologista,hematologia e hemoterapia}', area = 'clinica' WHERE nome = 'HEMATOLOGIA E HEMOTERAPIA';
UPDATE especialidades SET aliases = '{infectologia,infectologista,infecto}', area = 'clinica' WHERE nome = 'INFECTOLOGIA';
UPDATE especialidades SET aliases = '{mastologia,mastologista}', area = 'cirurgica' WHERE nome = 'MASTOLOGISTA';
UPDATE especialidades SET aliases = '{medicina de emergencia,emergencia,emergencista,urgencia}', area = 'clinica' WHERE nome = 'MEDICINA DE EMERGÊNCIA';
UPDATE especialidades SET aliases = '{medicina de familia,mfc,medicina de familia e comunidade,saude da familia}', area = 'clinica' WHERE nome = 'MEDICINA DE FAMÍLIA E COMUNIDADE';
UPDATE especialidades SET aliases = '{medicina do trabalho,medico do trabalho}', area = 'clinica' WHERE nome = 'MEDICINA DO TRABALHO';
UPDATE especialidades SET aliases = '{generalista,medica generalista,medico generalista,medicina generalista,sem especialidade}', area = 'clinica' WHERE nome = 'MEDICINA GENERALISTA';
UPDATE especialidades SET aliases = '{medicina intensiva,intensivista,uti,terapia intensiva}', area = 'clinica' WHERE nome = 'MEDICINA INTENSIVA';
UPDATE especialidades SET aliases = '{medicina legal,perito,pericia medica,medicina legal e pericia medica}', area = 'apoio' WHERE nome = 'MEDICINA LEGAL E PERÍCIA MÉDICA';
UPDATE especialidades SET aliases = '{nefrologia,nefrologista,nefro}', area = 'clinica' WHERE nome = 'NEFROLOGIA';
UPDATE especialidades SET aliases = '{neurologia,neurologista,neuro}', area = 'clinica' WHERE nome = 'NEUROLOGIA';
UPDATE especialidades SET aliases = '{oftalmologia,oftalmologista,oftalmo}', area = 'diagnostica' WHERE nome = 'OFTALMOLOGIA';
UPDATE especialidades SET aliases = '{ortopedia,traumatologia,ortopedista,ortopedia e traumatologia}', area = 'cirurgica' WHERE nome = 'ORTOPEDIA E TRAUMATOLOGIA';
UPDATE especialidades SET aliases = '{otorrinolaringologia,otorrino,otorrinolaringologista}', area = 'cirurgica' WHERE nome = 'OTORRINOLARINGOLOGIA';
UPDATE especialidades SET aliases = '{pediatria,pediatra,ped,pediatria/intensiva pediatrica}', area = 'clinica' WHERE nome = 'PEDIATRIA';
UPDATE especialidades SET aliases = '{pneumologia,pneumologista,pneumo}', area = 'clinica' WHERE nome = 'PNEUMOLOGIA';
UPDATE especialidades SET aliases = '{psiquiatria,psiquiatra}', area = 'clinica' WHERE nome = 'PSIQUIATRIA';
UPDATE especialidades SET aliases = '{radiologia,radiologista,radiologia e diagnostico por imagem,radio,diagnostico por imagem,medica radiologista,radiologista/ ultrassonografista,neurorradiologia}', area = 'diagnostica' WHERE nome = 'RADIOLOGIA E DIAGNÓSTICO POR IMAGEM';
UPDATE especialidades SET aliases = '{residente de anestesiologista,residente anestesio,r3 anestesio,residente anestesiologia}', area = 'residencia' WHERE nome = 'RESIDENTE DE ANESTESIOLOGISTA';
UPDATE especialidades SET aliases = '{residente de medicina de emergencia,residente emergencia}', area = 'residencia' WHERE nome = 'RESIDENTE DE MEDICINA DE EMERGÊNCIA';
UPDATE especialidades SET aliases = '{residente de pediatria,residente pediatra}', area = 'residencia' WHERE nome = 'RESIDENTE DE PEDIATRIA';
UPDATE especialidades SET aliases = '{reumatologia,reumatologista,reumato}', area = 'clinica' WHERE nome = 'REUMATOLOGIA';
UPDATE especialidades SET aliases = '{urologia,urologista,uro}', area = 'cirurgica' WHERE nome = 'UROLOGIA';
