
INSERT INTO licitacoes_etiquetas_config (nome, cor_id) VALUES
  ('COMPRASGOV', 'green'),
  ('BLL', 'green'),
  ('BLL COMPRAS', 'green'),
  ('BNC COMPRAS', 'green'),
  ('COMPRASBR', 'green'),
  ('COMPRAS RJ', 'green'),
  ('COMPRAS RS - PREGÃO ONLINE BANRISUL', 'green'),
  ('LICITAÇÕES-e', 'green'),
  ('LICITANET', 'green'),
  ('LICITAPP', 'green'),
  ('LICITAR DIGITAL', 'green'),
  ('PORTAL DE COMPRAS PUBLICAS', 'green'),
  ('PORTAL FAMESP/SP', 'green'),
  ('PORTAL SCPI', 'green'),
  ('AMM LICITA', 'green'),
  ('BB LICITAÇÕES', 'green'),
  ('BBMNET', 'green'),
  ('LICITA BELMONTE', 'green'),
  ('MENOR PREÇO GLOBAL', 'blue'),
  ('MENOR PREÇO POR ITEM', 'blue'),
  ('MENOR PREÇO POR LOTE', 'blue'),
  ('RADIOLOGIA', 'pink'),
  ('EXAMES', 'pink'),
  ('CONSULTAS', 'pink'),
  ('PLANTÕES', 'pink'),
  ('ULTRASSONOGRAFIA', 'pink'),
  ('Telemedicina', 'pink'),
  ('Teleconsulta', 'pink'),
  ('Teleconsultoria', 'pink'),
  ('Teleinterconsulta', 'pink'),
  ('Telerregulação', 'pink'),
  ('AGES', 'stone'),
  ('GSS', 'stone'),
  ('IMPUGNAR', 'red'),
  ('Impugnação', 'red'),
  ('Impugnação INDEFERIDA', 'red'),
  ('RECURSAR', 'red'),
  ('RECURSO', 'red'),
  ('JURÍDICO', 'red'),
  ('decisão judicial', 'red'),
  ('ORDEM JUDICIAL', 'red'),
  ('DESCARTAR', 'gray'),
  ('Fora do escopo', 'gray'),
  ('REPETIDO', 'gray'),
  ('REPROVADO', 'gray'),
  ('REVOGADO', 'gray'),
  ('SUSPENSO', 'orange'),
  ('VALOR BAIXO', 'orange'),
  ('VALOR ESTIMADO SIGILOSO', 'orange'),
  ('Presencial', 'green'),
  ('Credenciamento', 'teal'),
  ('Credenciamento enviado', 'teal'),
  ('DISPENSA', 'teal'),
  ('REGISTRO DE PREÇOS', 'teal'),
  ('ESTIMATIVA - FUTURO PREGÃO', 'yellow'),
  ('Aprovado', 'green'),
  ('CLT', 'purple'),
  ('FORNECER PACS', 'purple'),
  ('GARANTIA', 'yellow'),
  ('NECESSIDADE DE LOCAL', 'yellow'),
  ('SOMENTE ME/EPP (EXCLUSIVIDADE)', 'orange'),
  ('Esclarecimentos', 'yellow'),
  ('UNIDADE MÓVEL', 'purple'),
  ('DISTR DEMANDA-RODÍZIO', 'purple'),
  ('PRECIFICAÇÃO - POR HORA', 'blue'),
  ('VOLUMETRIA BAIXA', 'orange'),
  ('Assinatura ter sede!', 'orange'),
  ('Abaixo de 500mil/ANO', 'yellow'),
  ('Abaixo de 500mil/mês', 'yellow'),
  ('Acima de 1milhão', 'orange'),
  ('migrado do CLICKUP', 'gray'),
  ('MIGRADO TRELLO', 'gray')
ON CONFLICT DO NOTHING;

UPDATE licitacoes_etiquetas_config SET cor_id = 'pink' WHERE lower(nome) = 'radiologia';
